<?php
error_reporting(E_ALL);ini_set('display_errors', 1);
/*
 * @file
 * Module implementation.
 */

use Drupal\ddc_custom\EntityWrapper\Node\ArticleWrapper;

/**
 * Implements hook_node_access().
 */
function ddc_custom_node_access($node, $op, $account) {
  $article_wrapper = new ArticleWrapper($node->nid);
  return $article_wrapper->isPublished() ? NODE_ACCESS_IGNORE : NODE_ACCESS_DENY;
}

/**
 * Implements hook_node_view().
 */
function ddc_custom_node_view($node, $view_mode, $langcode) {
  switch ($node->type) {
    case 'article':
      $article_wrapper = new ArticleWrapper($node->nid);
      if (!$article_wrapper->isPublished()) {
        $node->content['#access'] = FALSE;
      }
      break;
  }
}